# Generated by Django 4.0.4 on 2022-05-30 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_skill_social_company_bio_company_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('post_type', models.CharField(choices=[('college', 'college'), ('job', 'job'), ('default', 'default')], default=('default', 'default'), max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.ManyToManyField(blank=True, to='base.skill'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='socials',
            field=models.ManyToManyField(blank=True, to='base.social'),
        ),
    ]
